### ISSUE TITLE
Sentry pillar forces Elysium to be Installed

### ISSUE THREAD

**Issue by ChaosNicro** [Dawars/CraftingPillars#3]
Using v1.6.1 the sentry pillar breaks worlds due to a forced compatibility with the Elysium mod.

Crashlog:

Time: 29.08.15 11:13
Description: Ticking block entity

java.lang.NoClassDefFoundError: hu/hundevelopers/elysium/Elysium
at me.dawars.CraftingPillars.api.sentry.GameProfileCompatibility.get(GameProfileCompatibility.java:14)
at me.dawars.CraftingPillars.api.sentry.FakeSentryPlayer.(FakeSentryPlayer.java:12)
at me.dawars.CraftingPillars.api.sentry.SentryBehaviorArrow.getProjectileEntity(SentryBehaviorArrow.java:30)
at me.dawars.CraftingPillars.api.sentry.SentryDefaultProjectile.spawnEntity(SentryDefaultProjectile.java:38)
at me.dawars.CraftingPillars.api.sentry.SentryDefaultProjectile.dispense(SentryDefaultProjectile.java:25)
at me.dawars.CraftingPillars.tiles.TileEntitySentryPillar.func_145845_h(TileEntitySentryPillar.java:79)
at net.minecraft.world.World.func_72939_s(World.java:1939)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: hu.hundevelopers.elysium.Elysium
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
... 13 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at me.dawars.CraftingPillars.api.sentry.GameProfileCompatibility.get(GameProfileCompatibility.java:14)
at me.dawars.CraftingPillars.api.sentry.FakeSentryPlayer.(FakeSentryPlayer.java:12)
at me.dawars.CraftingPillars.api.sentry.SentryBehaviorArrow.getProjectileEntity(SentryBehaviorArrow.java:30)
at me.dawars.CraftingPillars.api.sentry.SentryDefaultProjectile.spawnEntity(SentryDefaultProjectile.java:38)
at me.dawars.CraftingPillars.api.sentry.SentryDefaultProjectile.dispense(SentryDefaultProjectile.java:25)
at me.dawars.CraftingPillars.tiles.TileEntitySentryPillar.func_145845_h(TileEntitySentryPillar.java:79)

-- Block entity being ticked --
Details:
Name: TileEntitySentryPillar // me.dawars.CraftingPillars.tiles.TileEntitySentryPillar
Block type: ID #1732 (tile.sentryPillar // me.dawars.CraftingPillars.blocks.SentryPillarBlock)
Block data value: 0 / 0x0 / 0b0000
Block location: World: (67,70,-15), Chunk: (at 3,4,1 in 4,-1; contains blocks 64,0,-16 to 79,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Actual block type: ID #1732 (tile.sentryPillar // me.dawars.CraftingPillars.blocks.SentryPillarBlock)
Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1939)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
Level name: Testing
All players: 1 total; [EntityPlayerMP['NChaos'/220, l='Testing', x=65,93, y=70,00, z=-16,60]]
Chunk stats: ServerChunkCache: 625 Drop: 0
Level seed: 1552132858542756759
Level generator: ID 00 - default, ver 1. Features enabled: true
Level generator options:
Level spawn location: World: (80,69,-22), Chunk: (at 0,4,10 in 5,-2; contains blocks 80,0,-32 to 95,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Level time: 1243188 game time, 5026591 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 36694 (now: false), thunder time: 71480 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by IdleMuse** [comment]
Confirmed; seems to be related to https://github.com/Dawars/CraftingPillars/blob/master/java/me/dawars/CraftingPillars/api/sentry/GameProfileCompatibility.java

Which, despite noted as unused, is called here: https://github.com/Dawars/CraftingPillars/blob/master/java/me/dawars/CraftingPillars/api/sentry/FakeSentryPlayer.java

**Comment by ChaosNicro** [comment]
Using it should be ok, as long as there is something to catch the missing dependency and disable the reference. Witch there is not currently.
Is there any chance of getting an official fix with the author that inactive or would I need to clone and compile myself?
Thanks for looking into it by the way. ^^

**Comment by Dawars** [comment]
There is no official support, sorry.

It would be very cool if you could fix it or even continue / update / maintain the mod. :)

**Comment by IdleMuse** [comment]
I shall fork and fix this issue

**Comment by IdleMuse** [comment]
https://github.com/Dawars/CraftingPillars/pull/4 should fix for 1.7.10

Can use https://www.dropbox.com/s/9mi2xa24ctyajso/CraftingPillars-1.7.10-1.62.jar?dl=0 for now.
